/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * users.java
 *
 * Created on 3 Apr, 2011, 11:53:40 PM
 */

package hostel.ui;
import hostel.db.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author harshit
 */
public class users extends javax.swing.JFrame {
    public static String user_id;
    public static String password;
    /** Creates new form users */
    public users() {
        initComponents();
        actionListener e=new actionListener();
        focusListen f=new focusListen();
        passwd.addFocusListener(f);
        btnLogin.addActionListener(e);
        btnClear.addActionListener(e);
        btnExit.addActionListener(e);
        this.getRootPane().setDefaultButton(btnLogin);
        this.setLocationRelativeTo(null);
        this.pack();
        this.setTitle("Login Screen-Hostel Managemet System");


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        users = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwd = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Screen");
        setName("Login Screen"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18));
        jLabel1.setText("Login Screen");

        jLabel2.setText("User Name");

        jLabel3.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");

        btnExit.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwd)
                            .addComponent(users, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                .addContainerGap(89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnLogin)
                    .addComponent(btnClear))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField passwd;
    private javax.swing.JTextField users;
    // End of variables declaration//GEN-END:variables


    public class actionListener implements ActionListener
    {
        public void actionPerformed(ActionEvent e)
        {
            if(e.getSource()==btnClear){
                users.setText(null);
                passwd.setText(null);
            }

            if(e.getSource()==btnExit)
            {
                System.exit(0);
            }

            if(e.getSource()==btnLogin)
            {
                String usid=null,pas=null;
                user_id=users.getText();
                password=passwd.getText();
                int found=0;
                //String user_id=null,password=null;
                try{
                String query="select * from \"login\"";
                dbconnect db=new dbconnect(query);
                ResultSet res=db.exquery();
                //boolean t=res.next();
                

                while(res.next())//res.next()
                {
                    usid=res.getString("user_id");
                    pas=res.getString("password");
                    if(usid.compareTo(users.getText())==0
                            && pas.compareTo(passwd.getText())==0)
                    {
                        found=1;
                        break;
                    }

                }
                if(found==0){
                    JOptionPane.showMessageDialog(users.this, "Invalid Username/Password",
                            "Login Failed",JOptionPane.ERROR_MESSAGE);

                }
                else{
                    String uid=res.getString("user_id");
                    JOptionPane.showMessageDialog(users.this,"Logged on as "+usid,"Login Succeeded",
                            JOptionPane.INFORMATION_MESSAGE);
                    SWindow sw=new SWindow();
                    sw.setVisible(true);
                    users.this.setVisible(false);
                    users.this.dispose();
                    }
                }

                catch(SQLException p)
                {
                    p.printStackTrace();
                }
            }
        }
    }

private class focusListen implements FocusListener
{

        public void focusGained(FocusEvent e) {

            if(e.getSource()==passwd){
            passwd.setText("");
            }
        }

        public void focusLost(FocusEvent e) {
        }

}
}
